credentials:
  usernames:
    RKBobe:
      email: rkbeaubouef@gmail.com
      name: Kyle Beaubouef
      password: '$2b$12$9Am6qz2j63TZbb25Idi9heoWNppoCnLXmFylQ9HpGMli3oJz62a1K'
cookie:
  expiry_days: 30
  key: 'a_random_secret_key_123'
  name: 'beehav_auth_cookie'